---
- file: file
  paths:
    - platform: linux
      path: linux
    - platform: macos
      path: mac
    - platform: windows
      path: win
- file: file
  paths:
    - platform: linux
      path: linux
    - platform: macos
      path: mac
    - platform: windows
      path: win
